### PR TITLE
updated French language

### PR DESCRIPTION
**Pull request by elgatito**
It will probably never stop, so here is the pull for French update.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by scakemyer** [comment]
He got the banhammer anyway. I don't care if he was just dumb or a trollish f**ktard, I wasn't going to open that zippyshit link in the first place. And from what little knowledge I have of the French language and some quick Google translate checking, too many changes in there are wrong or just plain junk. Maybe @zorg1977 or @abuisine can pitch in or take it from here, but I'm not merging this as it is.

**Comment by elgatito** [comment]
Have no knowledge on french, but also was surprised of some translations. 
Would be good to get an edit from someone really "french".

**Comment by scakemyer** [comment]
Exactly, which is why I pinged the two previous contributors to French translations... either way it won't happen in this PR ;)

**Comment by abuisine** [comment]
I do confirm that there are a lot of mistakes :)
Let me propose another PR right away :P

**Pull request closed without merging**
