### PR TITLE
Translation update for Ukrainian, Translation update for Russian

### PR DESCRIPTION
**Pull request by elgatito**
Added Ukrainian language, update Russian language messages files.

I'm not sure if that is linked somehow, but Quasar restarts in a cycle when I browse it, with this in a log:
`
16:45:29.399 T:4976  NOTICE: [plugin.video.quasar] panic: interface conversion: interface {} is nil, not int
16:45:29.399 T:4976  NOTICE: [plugin.video.quasar]
16:45:29.399 T:4976  NOTICE: [plugin.video.quasar] goroutine 1 [running]:
16:45:29.400 T:4976  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/config.Reload(0xc0422a2720)
16:45:29.400 T:4976  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/config/config.go:184 +0x2c3a
16:45:29.400 T:4976  NOTICE: [plugin.video.quasar] main.main()
16:45:29.400 T:4976  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/main.go:87 +0x48d

`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Translation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by scakemyer** [comment]
I seriously doubt that's related, but can you try without your translations anyway? Otherwise, please file an issue with the complete log, that line in config.go doesn't match what I have here so I'll need to know which version you're running too.

**Comment by elgatito** [comment]
Latest version for windows x86, without changes, except the language.

**Comment by scakemyer** [comment]
Right, forgot I already pushed commits to master... So that line is about buffer_size, which means somehow in your settings.xml, buffer_size is just plain missing, and if that's the case you've got other issues too since it's the first setting to be processed.

**Comment by elgatito** [comment]
Yup, everything is fine. Probably I've moved files somehow or whatever.
Looks good with 0.9.70

**Comment by scakemyer** [comment]
Awesome, thanks for the translations!

**Comment by elgatito** [comment]
Possible there is a bug.
When I add something to the library I see only "LOCALIZE[30277]" text in the dialog window. I removed multi-line msgstr's (msgmerge composed that way to limit column-width for each line, I thought it's fine there), but nothing happen.
Tried both russian and ukrainian, while english is fine.
Quasar daemon uses resources of a plugin.quasar somehow? It should be rebuilt as well to notice changes in it's dialog windows?

**Comment by scakemyer** [comment]
Restarting Kodi usually updates translations just fine.

**Comment by elgatito** [comment]
Okay. I have got it. Any unicode text in 30277 causes that. I suppose python does not expect unicode there. I will go through the code.

**Comment by scakemyer** [comment]
That's probably my bad for not thinking about unicode in translations in [here](https://github.com/scakemyer/plugin.video.quasar/blob/master/resources/site-packages/quasar/util.py#L14-L28)

**Comment by elgatito** [comment]
Yupp. Trace got there for a:

`
10:22:06.790 T:3848   ERROR: [plugin.video.quasar] (quasar.rpc) In Handler method QuasarRPCServer.Dialog_Confirm(u'Quasar', u'LOCALIZE[30277];;24: Leg...)
10:22:06.792 T:3848   DEBUG: [plugin.video.quasar] C:\Program Files (x86)\Kodi\portable_data\addons\plugin.video.quasar\resources\site-packages\quasar\rpc.py::Dialog_Confirm:66 return dialog.yesno(getLocalizedLabel(title), getLocalizedLabel(message))
                                            C:\Program Files (x86)\Kodi\portable_data\addons\plugin.video.quasar\resources\site-packages\quasar\util.py::getLocalizedLabel:26 return translation % tuple(parts[1:])
10:22:06.792 T:3848   ERROR: [plugin.video.quasar] Unhandled error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 3: ordinal not in range(128)
`

**Comment by elgatito** [comment]
Placing msgstr in a next line works well. So strings can be splitted to fit in column width properly.

this is valid construction:

`
msgstr "This line "
" is joined without newline or space "
"or any other character"
`

**Comment by scakemyer** [comment]
Yeah it is, I knew that wasn't the problem, and those logs showed the exact line I thought was causing trouble

**Pull request merged**
