### PR TITLE
Keeping up

### PR DESCRIPTION
**Pull request by meijin007**
Sorry it's took me a while :)

### CODE REVIEW

**Comment by scakemyer** [comment]
`git commit --amend` then `git push --force` to say it's Hebrew updates, not just "Keeping up" ;)

**Comment by scakemyer** [comment]
Merged in 53bfb60

**Comment by meijin007** [comment]
Sorry, i won't do that next time :)

**Comment by scakemyer** [comment]
It's all good, but I'd appreciate it :)

**Pull request closed without merging**
