### PR TITLE
New day, new strings...

### PR DESCRIPTION
**Pull request by meijin007**

### CODE REVIEW

**Comment by scakemyer** [comment]
:+1: can you `git rebase -i` and squash (fixup actually) the second commit?

**Comment by meijin007** [comment]
Never used git rebase -i... will try :)

**Comment by scakemyer** [comment]
Please do, you'll feel like a pro once you get how it works :) The `-i` is for "interactive" which is a good way to start and more visual. Just replace the `pick` in from of the second commit, replace with `fixup` or just `f`, save, and enjoy :) Check the fixed up history with the usual git log and diff.

**Comment by meijin007** [comment]
done...any change?

**Comment by scakemyer** [comment]
Well, if it looks good on your end, you still need to push your changes ;) In this case you'll need to do a forced push.

**Comment by meijin007** [comment]
ok. I will start from the begging. will close this ne and send new PR.

**Comment by scakemyer** [comment]
Please don't, just push, it will update.

**Comment by meijin007** [comment]
I am always getting "Everything is up-to-date"... :\ sorry

**Comment by scakemyer** [comment]
Then your rebase didn't work and you still have the same two commits on your end also. Give it another try, and check with `git log` :)

**Comment by meijin007** [comment]
git log:
commit f948fc3617bc7980df0d88573690ba68e569c63d
Author: Assaf Sapir <meijin007@gmail.com>
Date:   Sun Jan 31 21:24:44 2016 +0200

    Added strings

commit 24bc092ea852df261867807dad8c9a6ec6e14613
Author: Assaf Sapir <meijin007@gmail.com>
Date:   Sun Jan 31 21:23:35 2016 +0200

    Added strings

commit 7005a5ed23da54d5bd7c8569b3275091128272bd
Merge: 9838dd5 8016a70
Author: scakemyer <scakemyer@tuta.io>
Date:   Sun Jan 31 11:39:12 2016 -0500

    Merge pull request #30 from i96751414/master
    
    Multi episodes strings - Fixes #17


Sorry for the mass :-1:

**Comment by scakemyer** [comment]
No worries, you'll get there, it's worth it :) So, retry `git rebase -i`, you should see your two commits there, then follow what I wrote about changing `pick` for `fixup`

**Comment by meijin007** [comment]
I don't have "pick" but "noop"...

**Comment by scakemyer** [comment]
Ah, my bad, since you already pushed.. `git rebase -i origin/master` maybe?

**Comment by meijin007** [comment]
same same...

**Comment by scakemyer** [comment]
replace `origin` with the name you gave my remote, check that with `git remote -v`

**Comment by meijin007** [comment]
assaf@laptop ~/git/1/plugin.video.quasar (git)-[master|rebase-i] % git remote -v
origin	https://github.com/meijin007/plugin.video.quasar.git (fetch)
origin	https://github.com/meijin007/plugin.video.quasar.git (push)

I am probably missing something here...

**Comment by scakemyer** [comment]
Right, yes. `git remote add scakemyer https://github.com/scakemyer/plugin.video.quasar.git`

Then `git rebase -i scakemyer/master`

**Comment by meijin007** [comment]
plugin.video.quasar (git)-[master] % git rebase -i scakemyer/master
fatal: Needed a single revision
invalid upstream scakemyer/master

**Comment by scakemyer** [comment]
Sorry, `git fetch scakemyer` .. too many things I just do automatically

**Comment by meijin007** [comment]
ok, then what?

**Comment by scakemyer** [comment]
Try `git rebase -i scakemyer/master` again

**Comment by meijin007** [comment]
I think I worked it out now?

**Comment by scakemyer** [comment]
:( four commits now.. I'm sorry I know using git isn't trivial in any way

**Comment by meijin007** [comment]
so "fixup" for all late 3?

**Comment by scakemyer** [comment]
That might work yeah, it's still the same changes so it should be good

**Comment by meijin007** [comment]
No good.. :\ 
git rebase -i scakemyer/master
Cannot 'fixup' without a previous commit

**Comment by scakemyer** [comment]
ok, the last thing made it worse so..
```
git checkout f948fc3617bc7980df0d88573690ba68e569c63d
git rebase -i scakemyer/master
```

**Pull request closed without merging**
