### PR TITLE
Update Portuguese (Brazil) translation

### PR DESCRIPTION
**Pull request by lrrosa**
Added missing msgids.
Improved some translations.

### CODE REVIEW

**Comment by KillerJoeBR** [comment]
Irrosa, are you having issues lately? In the latest version (0.9.11) i don't get the daemon started message. And the stream selection window doesn't work either. This started after your translation in 0.9.10 and mine 0.9.11 same thing happens. If i manually change the strings.po from version 0.9.9 everything works fine again.

Can you look if you have the same problems?

**Comment by lrrosa** [comment]
I have the same issue of daemon message and already discovered the problem. Quasar doesn't like the letter "ç" from serviço (msgctxt "#30208"). Replacing it with the letter c works. I'll open an issue about that.

About the stream selection this option isn't working for me either. Even when I choose other languages like english.

**Comment by KillerJoeBR** [comment]
Ok after your information about the ç letter, i updated the translation file using "c" instead of "ç" in all words. So i tested it again and the daemon message worked fine. 

But the available streams window still didn't work.  So i erased the line "available streams for" and the translation, and now the window works fine again. So it's maybe a different letter or something else in this line that cause the issues.

Anyway i don't mind keeping the original line if it just works. No big deal

**Comment by KillerJoeBR** [comment]
Ok so the problem in the streams selection window was the letter "í" in the word "disponíveis" . Replacing it with just "i" and now it works fine. 

So the problem only happens when using special letters in window dialogs (daemon started, streams available..etc...)

But it's better not using special letters anywhere just to be safe.

Irrosa , you probably need updating the providers for the streams selection window to work.

**Pull request merged**
