### PR TITLE
added description for binary not found. added activatewindow() 

### PR DESCRIPTION
**Pull request by elgatito**
Added new string in messages to show desired Platform when binary not found.
When remote control check fails - Opening Settings window.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
Thought to add more checks, but looks most places has info()/warning() calls.

**Comment by scakemyer** [comment]
Nitpicking: don't capitalize all new words, it's a way too common dev mistake to do so: `Required Platform` should just be `Required platform` and the only reason the first word gets capitalized is because it's on a new line. Don't `title()` the platform either, eg. `android_arm` should be left in lowercase.

I don't think opening the settings window helps in any way and will just confuse the user, since there's nothing more he could do in there to solve his issue. He needs to install a different package, not change a setting.

**Comment by elgatito** [comment]
Settings window is not for "binary not found", but for "enable both options", for json-rpc.
People often ask me what options they have to enable and where to find them.

**Comment by scakemyer** [comment]
My bad, nice one then!

**Comment by scakemyer** [comment]
Off the top of my head, since other translations don't have the placeholder for the platform_arch, I think Python is going to crap out on that. Might be worth doing away with a placeholder, and just append the platform_arch to a normal translation that just ends with `Required platform:`.

**Comment by scakemyer** [comment]
Can you make those changes? I'd like to get this in v0.9.75

**Comment by elgatito** [comment]
Updated. Somehow placeholder for a message.pot was not added previously, so that is fixed. 
English will come up as default.

**Comment by scakemyer** [comment]
I specifically asked to do this *without* placeholders since it's totally unnecessary in this case, and now there's two... :(

**Comment by scakemyer** [comment]
Every language that doesn't have an updated translation with a placeholder would break with a `not all arguments converted during string formatting` exception...

**Comment by scakemyer** [comment]
So update the english translation and `messages.pot` to:
```
msgid "Unable to find Quasar binary[CR]Required platform:"
```
And the notification line to:
```
notify(getLocalizedString(30103) + " %(os)s_%(arch)s" % PLATFORM), time=7000)
```
It's simple, will work with non-updated translations, will even look acceptable without any change, and doesn't add a single placeholder in translations.

**Pull request merged**
