### PR TITLE
added preselect transfer to dialog.select()

### PR DESCRIPTION
**Pull request by elgatito**
In Kodi17 python library was adjusted to use preselect in dialog.select() windows.
This commit adds autoclose+preselect parameter binding to use it in future from the daemon.

For Kodi < 17 dialog() logic is the same as it was before.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
Pros and Cons...
If preselect is defined, then clicking "cancel" still treats as user selected something. 
But using preselect will make things easier for user. Anyway, with "-1" nothing changes.
This works only on Kodi17.

**Comment by scakemyer** [comment]
I really don't think this is a good idea. Regular select dialog is only used when selecting a file within season packs for example, so we'd never want to preselect anything, much less force a selection when the user cancels. The first item already has focus in both Kodi 16 and 17, and if anything, later on for #703, we won't be going through the select dialog for that anyway. If we *do* want to preselect something for some reason, it'll actually be pre-focusing without making a selection. Also, you're passing those parameters pointlessly to Dialog_Select_Large, which is the custom Choose stream dialog.

**Comment by elgatito** [comment]
For me it's a big overhead when you open episode, but you don't have a good source to find separate episode stream, so you get a season stream, which just lists all the files. So you open 7th episode and have to find it in the list, then you switch to 8th and you do that once again. We can just use dummy S{season}E{episode} search through the files to find what we need and propose that to the user as a preselect or something.

**Comment by scakemyer** [comment]
I get that, my point is that it's not pre-select that you want, but pre-focus.

**Comment by scakemyer** [comment]
Having cancel being treated as having something selected makes this non-viable. Proper fix will be with #703.

**Pull request closed without merging**
