### PR TITLE
update hebrew

### PR DESCRIPTION
**Pull request by ShlomiD83**
fixed hebrew tanslation

### CODE REVIEW

**Comment by scakemyer** [comment]
Change the commit message please, first line mentions the language

**Comment by ShlomiD83** [comment]
like this?

**Comment by scakemyer** [comment]
Actually, the `Language` field is being changed from `he` to `he_IL` and you seem to be changing a lot of strings in there and leaving many of them empty where there was something. If this is a separate dialect then create it instead of messing up this one.

**Comment by scakemyer** [comment]
And that was the pull request's title that you changed, not the commit message...

**Comment by ShlomiD83** [comment]
i'm new a this, please be patient with me..

**Pull request closed without merging**
