### PR TITLE
added getShortPath to quasar.util to transform path depending on platform

### PR DESCRIPTION
**Pull request by elgatito**
… the platform

Added a getOsSpecificPath to quasar.util. 
Used to transform path, depending on the system.
Currently the only platform rule is for Windows.

For Windows:
Using ctype to transform usual path to short path. 

That fixes unicode chars issues, like #702.
Tested with my path, which was not working. 

Providers now can rely on this function to operate on windows with the same Kodi path.

## Related Issue

#702 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by scakemyer** [comment]
This looks both scary and very clever... I'm sure it would work just fine for regular ascii paths of other Windows users, but I'm wondering if this shouldn't be an explicit "I have a non-ascii Windows path" setting.

As for my typical code nitpicking, `getOsSpecificPath` looks too convoluted, and since it's Windows-only, I'd go with something like `getShortPath` instead. I'd also remove the blank line before `return path`.

So, since it's only for Windows, whether we go with a setting or not, I'd put the setting and/or platform check right in `start_quasard`, leaving the `args = [quasar_binary]` intact for other platforms and overriding after that instead.

**Comment by elgatito** [comment]
Updated the commit.

I'd leave PLATFORM detection in `getShortPath` to allow using it without problems in other places.

That `ctype` magic is not related to unicode in the path, it's just the way windows transform path into max-len-8-ascii format, so it won't break non-unicode path.

**Comment by scakemyer** [comment]
Yeah I get why you want platform detection there... looks a little redundant here but it makes sense to be used elsewhere...

**Comment by scakemyer** [comment]
Ah, wait, just use `getWindowsShortPath` here

**Comment by elgatito** [comment]
Take a look on a latest one.

**Comment by scakemyer** [comment]
Now that is more like it :+1:

**Pull request merged**
