### PR TITLE
New Show information fix

### PR DESCRIPTION
**Pull request by mancuniancol**
Sorry for the delay, but I am SVN guy.  Then, I am learning the git and I don't get the code updated easy.  But, anyway.  I've done the fix. I've used the poedit that I have to fix anything else.  Hope everything is ok right now.

### CODE REVIEW

**Comment by scakemyer** [comment]
There's that extra `.idea` folder.. will add to the .gitignore but for this PR:
```
git reset --soft @{1}
git reset HEAD .idea
git commit -m "New Show information fix"
git push --force
```

**Comment by mancuniancol** [comment]
Ok

**Comment by mancuniancol** [comment]
Done.

**Comment by scakemyer** [comment]
Nicely done ;)

**Comment by mancuniancol** [comment]
But, I still think that SVN is easier LOL

**Comment by scakemyer** [comment]
Wait... is there a hole in space-time? Are you in 2010?

**Comment by mancuniancol** [comment]
LOL, indeed.

**Pull request merged**
