### PR TITLE
Torrent files support

### PR DESCRIPTION
**Pull request by i96751414**

### CODE REVIEW

**Comment by i96751414** [comment]
@scakemyer don't get me wrong, you did a great work with pyxbmct, but we should get rid of that and make our own "dialogs".. I can make a dialog to replace that ono you made (pyxbmct)

**Comment by scakemyer** [comment]
Agreed, I just couldn't wrap my head around everything that was needed just to make a friggin' dialog box.

There's a few files being duplicated here tough, and I'd really like to replace the Close buttons of Confluence which look like they're straight from the 90s. I'd also like to keep the Aeon Nox one for List focus instead of the button-focus2.png of Confluence.

**Comment by i96751414** [comment]
Sure, those things can be easily changed. Originally I was using other close button (which I also prefer), but then I saw your pyxbmct dialog (and replaced the close button). About the duplicated files, I think there's no solution for now..

**Comment by scakemyer** [comment]
Of course there is ;) just point my stripped-down pyxbmct to the right path, it's right there at the top of addonwindow.py

**Comment by scakemyer** [comment]
To be honest I don't really like the XML window approach... it just hurts my brain.. Which is why I was going with Python-only windowing, trying to clean up pyxbmct and hoping to eventually make a good base class

**Comment by i96751414** [comment]
I understand, the thing is that you will be very limited using only python. A only python approach is great for simple things... Believe me, I tried to make the same window using pyxbmct and I could make one... But it was horrible

**Comment by scakemyer** [comment]
I'll be merging this today, just want to make a few changes to the other dialog at the same time

**Pull request merged**
