### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by razer1s**
Russian language

### CODE REVIEW

**Comment by scakemyer** [comment]
You're adding a file named " Russian" (with the space), instead of a folder with the strings.po file ;) It'd be great if the commit message mentioned you're adding the Russian language instead of just "strings.po". Thanks!

**Comment by scakemyer** [comment]
Could you rebase as one commit please?

**Comment by razer1s** [comment]
I don't understand what you mean

**Comment by scakemyer** [comment]
Merged in 5d847fd

**Pull request closed without merging**
