### PR TITLE
Update choose stream setting

### PR DESCRIPTION
**Pull request by i96751414**

### CODE REVIEW

**Comment by scakemyer** [comment]
Looks good, there's just the extra empty quotes I got rid of and it'd be great to not have them under some translations but not the others.

Again I really don't mean to be pain in the ass, but could you please rebase your commit instead of making a pull request of a merged pull request?

**Comment by i96751414** [comment]
You're right. I completely forgot about that.

**Comment by scakemyer** [comment]
No need to close the PR ;) Just rebase and force push :)

**Comment by scakemyer** [comment]
FYI, I'm adding Travis builds to cross-compiler, libtorrent-go and quasar. Struggling with Travis choking on logs but hopefully it will ease the pain of building the whole stack. Just send a PR to those repos to have Travis do all the hard work and test the changes, then either build locally and pull the compressed results from [Docker Hub](https://hub.docker.com/u/quasarhq/) when it's merged :)

**Comment by i96751414** [comment]
Ok, I've already rebased (and I won't forget about that next time) but it seems I can't force push for some reason.

**Comment by scakemyer** [comment]
If there's one thing that usually always works, for better or for worse, it's a forced push ;)

**Comment by i96751414** [comment]
Ok, sorry about that mess. It's finally done :) 
I really need to work more with git

**Comment by scakemyer** [comment]
Looks great, just needs the related changes in the daemon :)

**Comment by hfmls** [comment]
What's done?  ;)

**Comment by scakemyer** [comment]
See scakemyer/quasar#3 :)

**Comment by scakemyer** [comment]
Would it be worth it to make that Play string more descriptive, like "Play best stream" or something along those lines?

**Comment by i96751414** [comment]
Yeah, maybe... I guess it's up to you

**Pull request merged**
