### PR TITLE
Added 30228-30232

### PR DESCRIPTION
**Pull request by Greenbaburu**

### CODE REVIEW

**Comment by scakemyer** [comment]
Hey, could you provide the Quasar title as a png? I'll be making a homepage and could use some help with the graphics :)

**Comment by Greenbaburu** [comment]
like this? https://mega.nz/#!FlRDQBBB!MYh7kTR-fEMijzCY8-QM9jhoKCo0027uo9S81Zrhiko

**Comment by Greenbaburu** [comment]
<google.translate mode: ON>
"Quasar" on transparent background with very smooth shadow (maybe I misunderstood...)
Anyway, tell me (more specific you can) and i'll be very happy to provide what you need.
I'm eternally grateful for your amazing work with Quasar :)
</OFF>

**Comment by scakemyer** [comment]
Awesome, thanks! I don't really have a specific idea, just to make a nice, simple one-pager, with icons for Android / Linux / OSX / Windows and download links to the GitHub releases.

**Comment by scakemyer** [comment]
https://quasar.surge.sh/

**Comment by i96751414** [comment]
The website is great :) The only thing missing is responsiveness... At least when I've opened it with my phone, the website got deconfigured

**Comment by scakemyer** [comment]
Yeah it's not responsive yet, just a very simple one-pager. Will fix it. Want to make an issue for it? ;)

**Comment by i96751414** [comment]
I can do it :) You could create a repo so we can also contribute to your site (although it's a simple site)

**Comment by scakemyer** [comment]
I was going to do that today. It's using HarpJS so you might want to get that installed if you want to work on it :)

**Comment by hfmls** [comment]
wow, that's pretty cool. Great job doing all this guys, all of you helping. I see bright future for QASAR, just a couple of weeks and it's already pretty cool.

**Pull request merged**
