### PR TITLE
new methods for providers

### PR DESCRIPTION
**Pull request by mancuniancol**
I'm adding several methods and class to make lighter and faster the providers.  It also make writing easier.  I don't change previous methods, then it will be compatible with the current ones.

### CODE REVIEW

**Comment by scakemyer** [comment]
I'm really sorry but I can't merge this. Even if it wasn't for the 53 linting errors and the build actually passed, this is way too specific to providers and would definitely push Quasar on the other side of the fine line we're dealing with. Please consider making a separate dependency for your providers instead; only the bare, current minimum should be in Quasar itself.

**Comment by mancuniancol** [comment]
I don't share your affirmation, because Quasar already have that in the provider.py. I'm just enchanting the methods. 

But, I won't insist. 

Any case,  I want to know about the linting errors.I don't have any reported  in my side. Could you share the report at least.

**Comment by scakemyer** [comment]
The report is the Travis build, just click on the red X beside your commit above. Either way you've solved all of this with Magnetic and then some. Nice work, it's a much cleaner and better approach :)

**Comment by mancuniancol** [comment]
Ok, thank you for the feedback

**Pull request closed without merging**
