### PR TITLE
Update choose stream dialog

### PR DESCRIPTION
**Pull request by i96751414**

### CODE REVIEW

**Comment by scakemyer** [comment]
Can't wait to merge this, looking into it in a few minutes

**Comment by scakemyer** [comment]
I'll probably replace the scrollbar images with the ones from Aeon Nox. Confluence looks awful with other themes and Nox is a lot more neutral.

**Comment by scakemyer** [comment]
Is the amount of padding intentional?

**Comment by i96751414** [comment]
Sure, go ahead. Please also delete line 80 from the xml file (i'm not at the pc right now)

**Comment by i96751414** [comment]
Yes, it is. Buti can change that tomorrow

**Comment by scakemyer** [comment]
Ok just wanted to check, don't worry about it I'll be pushing this tonight. I'll probably go with something in between, I agree that a little padding was missing.

**Pull request merged**
