### PR TITLE
Adjusting Show Information/Movie Information to Information...

### PR DESCRIPTION
**Pull request by mancuniancol**
I've found that Show information is also used for the movies and the initials translations were done using movie information. I've unified just to information... to make easy to fix in all language and it will be the same for movies or tv shows

### CODE REVIEW

**Comment by i96751414** [comment]
See this please: https://github.com/scakemyer/plugin.video.quasar/commit/11bb663efaf6324efdad938a396257bd6d3f23d8#commitcomment-15789525

**Comment by mancuniancol** [comment]
@i96751414, that is my point.  In English it says "Show information", but the translation are still referring to "Movie Information".

**Comment by scakemyer** [comment]
msgid must remain "Show information"

**Comment by mancuniancol** [comment]
Then I speak also Spanish and French. I will fix those languages. I will try to figure with Google translation the rest. But, I confirm the translation is about movie information.

**Comment by mancuniancol** [comment]
For that reason,  it was easy just to leave information, but I think won't be easy to find out the right translation for show more information

**Pull request closed without merging**
