### PR TITLE
Multi episode string Dutch

### PR DESCRIPTION
**Pull request by peer23peer**
Hi.

Tried it with `git rebase -i`  it now shows 1 commit but 4 changed files...

if I did it wrong pls let me know. Love to help but don't wanna mess things up

### CODE REVIEW

**Comment by scakemyer** [comment]
That's close but not quite, still two commits here. You're getting there. Following the other discussion about rebase? Think it might help also.

**Comment by peer23peer** [comment]
Better???

**Comment by scakemyer** [comment]
Really sorry, I know I'm being very picky but no.. checked out your PR and the history is messed up:
```
commit 6f5b82e8ec4e87e3d3ed0a31c6ea6e9d81d177af
Merge: 7005a5e e04f07e
Author: Jelle Spijker <spijker.jelle@gmail.com>
Date:   Sun Jan 31 20:06:46 2016 +0000

    Merge e04f07e45adf3ee64ac42e1b3bcb9384cec6e8f3 into 7005a5ed23da54d5bd7c8569b3275091128272bd

commit e04f07e45adf3ee64ac42e1b3bcb9384cec6e8f3
Author: i96751414 <i96751414@gmail.com>
Date:   Sun Jan 31 15:51:01 2016 +0000

    Multi episodes strings - Fixes #17

commit 7005a5ed23da54d5bd7c8569b3275091128272bd
Merge: 9838dd5 8016a70
Author: scakemyer <scakemyer@tuta.io>
Date:   Sun Jan 31 11:39:12 2016 -0500

    Merge pull request #30 from i96751414/master
    
    Multi episodes strings - Fixes #17

commit 8016a70f1377747a4739d277e67de4e6b157599d
Author: i96751414 <i96751414@gmail.com>
Date:   Sun Jan 31 15:51:01 2016 +0000

    Multi episodes strings - Fixes #17
```

**Comment by peer23peer** [comment]
Don't be sorry, I appreciate the coaching you do. I don't know how undo my mesh. So maybe it's best if I delete my fork, create a new one and put in an other pull request.

Now this is bound to happen again. Could you tell me the proper way to update my fork with commits from somebody else and how to present mine?

thank you

**Comment by scakemyer** [comment]
Of course, glad you're taking it well. No need to open a new PR though, you can delete your local branch (keep your changed files in a patch or something!), checkout a fresh copy, a push over your repo to update this same PR.

**Comment by scakemyer** [comment]
So, here's what should work for you:
```
git remote add scakemyer http://github.com/scakemyer/plugin.video.quasar.git
git checkout -b scakemyer scakemyer/master
git branch -D master
git checkout scakemyer
git branch -m master
```

**Comment by scakemyer** [comment]
That's to start over from the master branch of this repo, so make sure your changes are saved elsewhere.

**Comment by peer23peer** [comment]
```
peer23peer@peerLaptop:~/git/plugin.video.quasar(master)$ git remote add scakemyer http://github.com/scakemyer/plugin.video.quasar.git
peer23peer@peerLaptop:~/git/plugin.video.quasar(master)$ git checkout -b scakemyer scakemyer/master
fatal: Cannot update paths and switch to branch 'scakemyer' at the same time.
Did you intend to checkout 'scakemyer/master' which can not be resolved as commit?
```

In other words... arggggggggggggghhhh.. could you recommend a good book or tutorial site? 

How do I clear all my messed up #$#! and revert it all back to my initial state. I tried it with rebase by removing the previous commits maybe that is why your suggestion don't work anymore

**Comment by scakemyer** [comment]
crap, `git fetch scakemyer` first.. made the same mistake with meijin007, my bad

**Comment by scakemyer** [comment]
About rebase vs merge: http://mislav.net/2013/02/merge-vs-rebase/
His tips are clear too: http://mislav.net/2013/02/merge-vs-rebase/

As far as general tutorials go, I'm afraid you'll have to search for one that you like, there are plenty of good ones around. The official git docs are tedious and confusing at best.

**Comment by peer23peer** [comment]
Okay I performed the following steps:
```
git remote add scakemyer http://github.com/scakemyer/plugin.video.quasar.git
git fetch scakemyer
git checkout -b scakemyer scakemyer/master
git branch -D master
git checkout scakemyer
git branch -m master
```

Made my changes to Dutch\strings.po

```
git stage .
git commit -m "Dutch string for "Files""
```

now if i want to push I'm on your fork and believe me I understand why you don't want anyone to randomly push things on to it.
Is it okay to assume I now have to switch the remote to my own fork and 'git push --force' there?
Then make a new PR?

**Comment by scakemyer** [comment]
You can't just push to my fork so no worries there ;) And `git push` will use your own remote by default, so you should be able to just `git push --force`

**Comment by peer23peer** [comment]
```
peer23peer@peerLaptop:~/git/plugin.video.quasar(master)$ git push --force
Username for 'https://github.com': peer23peer
Password for 'https://peer23peer@github.com': 
remote: Permission to scakemyer/plugin.video.quasar.git denied to peer23peer.
fatal: unable to access 'https://github.com/scakemyer/plugin.video.quasar.git/': The requested URL returned error: 403
```

**Comment by scakemyer** [comment]
F***.. you were right.. need to make it track your fork for it to push to it.. `git branch --set-upstream-to=<your remote>`

**Comment by peer23peer** [comment]
What do you mean with `<your remote>` exactly ? I tried:
-  git@github.com:peer23peer/plugin.video.quasar.git
-  https://github.com/peer23peer/plugin.video.quasar.git
-  peer23peer/master

all to no avail

**Comment by scakemyer** [comment]
it's the *name* of the remote, list them with `git remote -v`, the name are the left

**Comment by peer23peer** [comment]
`origin`
yes

**Comment by scakemyer** [comment]
success!

**Comment by peer23peer** [comment]
To recap next time I want to contribute. I can now 
```
git fetch scakemyer
git checkout -b scakemyer scakemyer/master
git branch -D master
git checkout scakemyer
git branch -m master
```

perform my changes.

```
git stage .
git commit
```

And make a new pull request

correct?

**Comment by scakemyer** [comment]
No that was really just to start fresh this time around. Use `git pull scakemyer` before making changes, or `git pull --rebase scakemyer` if you've made them already.

**Comment by peer23peer** [comment]
Cheers will do

**Pull request merged**
