### PR TITLE
Fix hebrew, Add new strings...

### PR DESCRIPTION
**Pull request by meijin007**
Sorry :+1:

### CODE REVIEW

**Comment by scakemyer** [comment]
Translations look good, will `"Language: he\n"` being changed to `"Language: he_IL\n" affect things?

**Comment by meijin007** [comment]
No idea. better keep what it was...

**Comment by scakemyer** [comment]
I think so too. Do you mind cleaning up the headers while fixing that? I like that some fields like the date and author gets updated, but it'd be great to keep the part at the top. Maybe just paste after the first four lines when you update them. Not sure what your process is so let me know if anything else can be improved :)

**Comment by meijin007** [comment]
I am using some tool for translating, so this is probably its "fault".
i will fix it.

**Comment by scakemyer** [comment]
I guessed it was, no worries :)

**Comment by meijin007** [comment]
Better Now? :)

**Comment by scakemyer** [comment]
Purrfect

**Pull request merged**
