### PR TITLE
fix for watched state setters

### LINKED ISSUE #833: New episodes are not being marked as watched
Hi there, it's me again.

So i did some testing with the new release and it does work for not-so-new episodes. They get marked as watched just fine. But it's not working for recent ones. 

It doesn't show the bad status message like before, but after playback it's not being marked as watched. And i'm pretty sure it worked fine before the 0.9.76 release. (i would need to install it again to be sure, but i'm 90% sure it was working for recent episodes just fine)

My Quasar scraper is TVDB wich is also my library scraper. TVDB is the oficial default kodi scraper for series, right? So it should work with this one i think. 

Later i can get a log, but i think it would look just like the ones before. But just ask for one and i will provide.

Thanks

### PR DESCRIPTION
**Pull request by elgatito**
Fixes #833, #832, #821 and other issues, connected with watched state. 

## Description

Changes in plugin:
- If item was called from Kodi library - information is used "as is", proxying all the data to the player.
- Fixed setting integer values, Player.setInfo() needs all as string, so int values were skipped.
- Moved Player.Pause() to be executed only on /play urls (so when item is played and you browse Quasar - video will not be paused automatically).

Changes in backend:
- Watched status is updated on every torrentfs close(), but now we take DBID, DBTYPE from Player() (those fields are now correctly set by navigation.py and are describing currently playing item).
- Moved UniqueId getter for TVShows to separate function.
- If TMDB item does not have TVDB Id link (for example, for new episodes), then we try to iterate Show's episodes and match by Season+Episode.

Would be great to involve users to testing. @KillerJoeBR, maybe?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KillerJoeBR** [comment]
Hi there elgatito. I would love to test this fix. Just tell me how I can download and apply this fix so I can test it. Yeah I'm pretty much a newbie. 

Thanks

**Comment by KillerJoeBR** [comment]
Well I think I got it right, downloaded Quasar from your fork. 

I did some tests and it seems to be working alright now.  It identifies the title of the episode and after watching it got marked as so. Then I tried watching a movie from the recent widget in the home menu and it also worked okay. But it didn't work in the recent widget for series episode in the home menu. It didn't get marked as watched and during playback it didn't show the episode title. Tried the same episode inside the library and it worked fine. 

So it seems to be working great everywhere except using the home menu widget for TV episodes. 

I will try to do more tests but my time is very limited right now, so I can't promise. But I'm almost sure it's working great now

**Comment by elgatito** [comment]
Would be great if you show a log file to see how it does there.

**Comment by elgatito** [comment]
Tried running episode from "recent episodes" widget and got it initialized. Need you log to see what Quasar do to resolve episode.

**Comment by elgatito** [comment]
@KillerJoeBR  have you tried to build and replace Quasar binary as well? Or only the python part?

**Comment by KillerJoeBR** [comment]
Well like I said I'm a newbie. I was happy that I got it working but I don't know if I did it completely right. I downloaded Quasar from your fork as zip then I opened it and included the arm Linux bin from the official Quasar 0.9.78 release. I don't know how to build it like you said.

**Comment by KillerJoeBR** [comment]
Maybe you could just send me the Quasar already updated with your fix and I test it here.

**Comment by elgatito** [comment]
I'm out of workstation till monday. If @scakemyer won't come overtill that time - I will make you a binary.
You use linux_x64 Quasar version?

**Comment by KillerJoeBR** [comment]
x32 arm android version

**Comment by elgatito** [comment]
Here is the binary. Just replace existing binary at `addons/plugin.video.quasar/resources/bin/linux_x64/` and restart Kodi.
[android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/1017848/android_arm.zip)

**Comment by KillerJoeBR** [comment]
Ok thanks. I will test it later when I get home. BTW I don't know why I said Linux binary earlier. Its just Android arm. Just to be clear and if this binary will work for me (android arm) 

Thanks

**Comment by KillerJoeBR** [comment]
Sorry, i'm really busy right now, but i did some tests and the same thing happened. Everything works okay, except while playing from the series widget in the home menu. If i play inside the library it gets the episode title and after playback it gets marked as watched. But using the episode widget it plays but i don't get the episode title in the description (just generic "season X episode XX") and it doesn't get marked as watched after playback.

(I will try to get a log later)

**Comment by elgatito** [comment]
Will wait for logs to see the details. That is with binary new?

**Comment by elgatito** [comment]
Also make sure if your scraper for Shows is TVDB then it is set in Quasar settings.

**Comment by elgatito** [comment]
I think I have found a bug, so you can try with a newer version:
[android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/1028107/android_arm.zip)

**Comment by KillerJoeBR** [comment]
Ok I tried some more and indeed it is working from series widget. I doesn't get the title description but it does get marked as watched after playback. 

But when I tested it for episodes of the series Billions it didn't work. So maybe it was working before this new updated binary but I tested it before with the series billions and it doesn't work. It did work for every other series that I tried now. But for a reason it doesn't work with the series billions

**Comment by elgatito** [comment]
I would appreciate a log file.

**Pull request closed without merging**
