### PR TITLE
hebrew fix

### PR DESCRIPTION
**Pull request by yokod**

### CODE REVIEW

**Comment by meijin007** [comment]
@yokod 1) you have some typos. 2) did you ever translated software before?
@scakemyer Please don't merge this yet.

**Comment by scakemyer** [comment]
@meijin007 I wasn't going to, too many changes after all the work you've done, so somehow I knew you wouldn't approve ;) Merged yours and now this one conflicts.

I appreciate you're trying to contribute @yokod but @meijin007 has been the most active translator so I know only small changes would be needed for Hebrew. I don't know how many dialects you guys have, but along with another PR I closed, it seems this one should be a different kind of Hebrew.

**Comment by meijin007** [comment]
There ia only one dielect in Hebrew :)

**Comment by scakemyer** [comment]
translations

**Pull request closed without merging**
