### PR TITLE
Show information fix

### PR DESCRIPTION
**Pull request by mancuniancol**
OK, The changes were done. I am not 100% sure about the Hebrew translation, though.  But the rest is ok.

### CODE REVIEW

**Comment by scakemyer** [comment]
Hebrew had already been fixed in 6a11c188

**Comment by mancuniancol** [comment]
It seems that it is a lot people helping.  That is cool.  Well, I will try to be more careful with my pull request :)

**Comment by scakemyer** [comment]
Do you mind changing it back before I merge this?

**Comment by mancuniancol** [comment]
Not at all

**Pull request closed without merging**
